language: node_js
node_js:
  - node
os: linux

notifications:
  email: false

jobs:
  include:
    - stage: Compile and Test
      script: npm run test && bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/clover.xml
stages:
  - Compile and Test
